# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        working-directory: ./source
        run: |
          npm i --include=dev

      - name: Run markdown linting
        working-directory: ./source
        run: |
          npx remark . --use remark-preset-lint-consistent --frail

      - name: Run html linting (htmlhint)
        working-directory: ./source
        run: |
          npx htmlhint "**/*.html"
      
      - name: Run javascript linting (eslint/prettier)
        working-directory: ./source
        run: |
          npx eslint .
          npx prettier --check .

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        working-directory: ./source
        run: |
          npm i

      - name: Run javascript tests (jest)
        working-directory: ./source
        run: |
          npx jest --testEnvironment='jsdom'
