# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run markdown linting
        run: |
          npm i remark-cli remark-preset-lint-consistent
          npx remark . --use remark-preset-lint-consistent --frail

      - name: Run html linting (htmlhint)
        run: |
          npm i htmlhint
          npx htmlhint "**/*.html"

      - name: Run css linting (stylelint)
        run: |
          npm i stylelint stylelint-config-standard
          npx stylelint "**/*.css"
      
      - name: Run javascript linting (eslint)
        run: |
          npm i eslint
          npx eslint .

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run javascript tests (jest)
        run: |
          npm i jest jest-environment-jsdom
          npx jest --testEnvironment='jsdom'
